INSERT INTO CATEGORY (description) VALUES ('American');
INSERT INTO CATEGORY (description) VALUES ('Italian');
INSERT INTO CATEGORY (description) VALUES ('Mexican');
INSERT INTO CATEGORY (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('Pound');
INSERT INTO unit_of_measure (description) VALUES ('Each');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO unit_of_measure (description) VALUES ('Quart');
INSERT INTO unit_of_measure (description) VALUES ('Gallon');
INSERT INTO unit_of_measure (description) VALUES ('Milliliter');
INSERT INTO unit_of_measure (description) VALUES ('Liter');
INSERT INTO unit_of_measure (description) VALUES ('Deciliter');
INSERT INTO unit_of_measure (description) VALUES ('Centiliter');
INSERT INTO unit_of_measure (description) VALUES ('Milligram');
INSERT INTO unit_of_measure (description) VALUES ('Gram');
INSERT INTO unit_of_measure (description) VALUES ('Kilogram');
INSERT INTO unit_of_measure (description) VALUES ('Milliliter');
INSERT INTO unit_of_measure (description) VALUES ('Cubic Centimeter');
INSERT INTO unit_of_measure (description) VALUES ('Cubic Inch');
INSERT INTO unit_of_measure (description) VALUES ('Cubic Foot');
INSERT INTO unit_of_measure (description) VALUES ('Cubic Yard');
INSERT INTO unit_of_measure (description) VALUES ('Fluid Ounce');